### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by niuchp** [gzhaha/myBase-Plugins#6]
希望能增加一个锁定条目的功能。
存在mybase中的内容大多数的不经常修改的知识条目，没有锁定功能，很容易误操作修改内容。只读方式又不便于新增条目。因此，一个针对于单个条目的编辑开关很重要。

**Comment by gzhaha** [comment]
在【选项】-》【内容】-》不勾选【打开缺省HTML内容时自动进入编辑状态】即可实现类似功能

**Comment by niuchp** [comment]
@gzhaha thinks.
